# 一、异常处理

- 默认处理方式：当程序的执行过中产生异常时，若没有手动进行处理，则有Java虚拟机默认方式处理

```java
package com.maqf.demo01;

public class Demo01 {
    public static void main(String[] args) {
        System.out.println("start");
        method();
        System.out.println("end");
    }

    private static void method() {
        // 数组下标越界，非监测性异常
        int[] arr = new int[10];
        arr[12] = 1;
    }
}
```

- 手动处理方式：想怎么处理都可以

```java
package com.maqf.demo01;

public class Demo02 {
    public static void main(String[] args) {
        System.out.println("start");
        method();
        System.out.println("end");
    }

    private static void method() {
        // 数组下标越界，非监测性异常
        int[] arr = new int[10];
        try {
            arr[12] = 1;
        } catch(Exception e) {
            System.err.println(e);
            // System.err.println("Array index out of bounds exception");
        } finally {
            System.out.println("finally");
        }
    }
}
```

# 二、异常类

- java.lang.Throwable类是Java程序所有错误的父类，主要有Error和Exception类
	- Error类：主要描述比较严重的错误，不可以通过编程来解决的重大问题
	- Exception类：主要描述比较轻量级的错误，可以通过编程来解决

# 三、Exception的主要分类

- RuntimeException，运行时异常类，非检测性异常类，在编译阶段无法被检测出来的异常
	- ArithmeticException - 算数异常类
	- ArrayIndexOutOfBondsException - 数组下标越界异常
	- NullPointerException - 空指针异常
	- ClassCastException - 类型转换异常
	- NumberFormatException - 数字格式异常
- IOException和其他异常类，检测性异常类（例如：FileInputStream类new对象时产生的异常）

```java
package com.maqf.demo01;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

public class Demo03 {
	// 检测性异常处理
    public static void main(String[] args) throws IOException {
        FileReader fr = null;
        // 一般直接抛出，有特殊要处理的点用try catch手动抛出
        try {
            fr = new FileReader("./myTest.txt");
        } catch(FileNotFoundException e) {
            e.printStackTrace();
        }
        int read = fr.read();
        System.out.println(read);
        fr.close();
    }
}
```

# 四、异常的解决方案

- 通过条件判断来避免异常的出现
- 通过try、catch捕获异常并处理
```java
try{}catch(异常对象){}finally{}
```

# 五、异常的抛出

- 当异常产生后无法直接处理或者不想直接处理时，此时可以将异常转移全当前方法的调用者
- 格式：`返回值 方法名 (参数列表) throws 异常类型 {方法体}`
- 方法重写的时候抛出的异常不能大于被 重写方法抛出的异常

# 六、自定义异常类

- 解决Java官方库中没有描述的异常
- 语法：`throw new Exception();`
- 自定义Exception类
- 继承Exception类并设置构造方法，有参（调用父类中的有参构造方法）、无参

```java
package com.maqf.demo02;

public class Student {
    private String name;
    private int age;

    public int getAge() {
        return this.age;
    }

    public void setAge(int age) throws AgeException {
	    // 抛出自定义异常
        if (age <= 0 || age > 150) {
            throw new AgeException("Age Error");
        }
        this.age = age;
    }
}
```

```java
package com.maqf.demo02;

// 自定义异常类
// 如果是继承运行时异常RuntimeException，就不用向外抛，运行时才会检测出来
public class AgeException extends Exception {
    AgeException() {}

    AgeException(String errMess) {
        super(errMess);
    }
}
```

```java
package com.maqf.demo02;

public class Demo01 {
    public static void main(String[] args) throws AgeException {
        Student stu = new Student();
        // 设置age时可能会出现异常，直接抛出或手动处理
        stu.setAge(0);
        System.out.println(stu.getAge());
    }
}
```